name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: "NodeJS"
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: 'Version and Deploy'
      run: |
        npx lerna version --conventional-commits --yes
        npx lerna publish from-git --yes